"""Turns a sprite sheet made elsewhere (e.g. generated by an AI image tool, or drawn at any size)
into the game's 50x50 frames: removes a flat background, cuts the frames, shrinks each one to
the player's height with its feet on the same line, limits the palette so it stays pixel art,
and saves them with the names the game uses.

    python3 scripts/import-sprite-sheet.py policial.png
    python3 scripts/import-sprite-sheet.py policial.png --frames 6 --names cop-run-1,cop-run-2,cop-run-3,cop-run-4,cop-shout,cop-catch --out src/assets/sprites/cop

The sheet should have the frames side by side, in one row, left to right, on a flat background
(or transparent). After importing, run `npm run sprites` inside mobile/ to update the app.
Needs Pillow (pip install pillow).
"""
import argparse
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SIZE = 50  # frame size, like src/assets/sprites/walk/*.png
CHARACTER_HEIGHT = 44  # the player is ~44px tall inside its 50px frame
FEET_Y = 48  # last row of the feet
DEFAULT_NAMES = "cop-run-1,cop-run-2,cop-run-3,cop-run-4,cop-shout,cop-catch"


def remove_background(image: Image.Image, tolerance: int) -> Image.Image:
    """Makes the flat background transparent (the color of the corners), unless it already is,
    then eats the soft fringe of background color left around the drawing."""
    image = image.convert("RGBA")
    px = image.load()
    w, h = image.size
    corners = [px[0, 0], px[w - 1, 0], px[0, h - 1], px[w - 1, h - 1]]
    if all(c[3] < 16 for c in corners):
        return image  # already transparent
    bg = max(set(corners), key=corners.count)

    def distance(c):
        return max(abs(c[0] - bg[0]), abs(c[1] - bg[1]), abs(c[2] - bg[2]))

    for y in range(h):
        for x in range(w):
            if distance(px[x, y]) <= tolerance:
                px[x, y] = (0, 0, 0, 0)
    # Fringe: pixels still tinted by the background, next to the removed area.
    for _ in range(3):
        fringe = []
        for y in range(1, h - 1):
            for x in range(1, w - 1):
                c = px[x, y]
                if c[3] and distance(c) <= tolerance * 3 and (
                    px[x - 1, y][3] == 0 or px[x + 1, y][3] == 0 or px[x, y - 1][3] == 0 or px[x, y + 1][3] == 0
                ):
                    fringe.append((x, y))
        for x, y in fringe:
            px[x, y] = (0, 0, 0, 0)
    return image


def to_frame(cell: Image.Image, colors: int) -> Image.Image:
    box = cell.getbbox()
    frame = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    if not box:
        return frame
    art = cell.crop(box)
    scale = CHARACTER_HEIGHT / art.height
    width = max(1, round(art.width * scale))
    if width > SIZE - 2:  # very wide poses (arms out) still fit the frame
        scale = (SIZE - 2) / art.width
        width = SIZE - 2
    height = max(1, round(art.height * scale))
    # Area-average the big drawing down (premultiplied, so transparent pixels don't darken the
    # edges), then snap alpha and colors back to hard pixels.
    small = art.convert("RGBa").resize((width, height), Image.BOX).convert("RGBA")
    alpha = small.getchannel("A").point(lambda a: 255 if a >= 128 else 0)
    # The palette comes from the drawing only: transparent pixels are filled with its main color.
    opaque = [c[:3] for c, a in zip(small.getdata(), alpha.getdata()) if a]
    fill = max(set(opaque), key=opaque.count) if opaque else (0, 0, 0)
    rgb = Image.new("RGB", small.size, fill)
    rgb.paste(small.convert("RGB"), mask=alpha)
    rgb = rgb.quantize(colors=colors, method=0).convert("RGB")  # 0 = median cut (old and new Pillow)
    small = rgb.convert("RGBA")
    small.putalpha(alpha)
    frame.alpha_composite(small, ((SIZE - width) // 2, FEET_Y + 1 - height))
    return frame


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("sheet", type=Path)
    parser.add_argument("--frames", type=int, default=6, help="frames side by side in the sheet (default 6)")
    parser.add_argument("--names", default=DEFAULT_NAMES, help="file names for the frames, left to right")
    parser.add_argument("--out", type=Path, default=ROOT / "src/assets/sprites/cop")
    parser.add_argument("--colors", type=int, default=16, help="palette size per frame (default 16)")
    parser.add_argument("--tolerance", type=int, default=40, help="how close to the background color gets removed")
    args = parser.parse_args()

    names = [n.strip() for n in args.names.split(",") if n.strip()]
    if len(names) != args.frames:
        parser.error(f"{args.frames} frames but {len(names)} names")

    sheet = remove_background(Image.open(args.sheet), args.tolerance)
    cell_width = sheet.width / args.frames
    args.out.mkdir(parents=True, exist_ok=True)
    for i, name in enumerate(names):
        cell = sheet.crop((round(i * cell_width), 0, round((i + 1) * cell_width), sheet.height))
        to_frame(cell, args.colors).save(args.out / f"{name}.png")
        print(f"{args.out / name}.png")
    print("Pronto. Rode `npm run sprites` dentro de mobile/ para atualizar o app.")


if __name__ == "__main__":
    main()
